= Hawkular

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories and integrated in this project.

Sub-projects are currently:

* https://github.com/hawkular/hawkular-metrics[Hawkular-metrics]: metric storage and retrieval engine
* https://github.com/hawkular/hawkular-bus[Hawkular-bus]: asynchronous bus to connect the various parts
* https://github.com/hawkular/hawkular-alerts[Hawkular-alerts]: alerting on events.
* https://github.com/hawkular/hawkular-build-tools[Hawkular build tools]: Helpers and definitions to build Hawkular

== About this repository

In this repository we are assembling the individual pieces, sub projects and UI into
the overall Hawkular instance

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular]
image:https://travis-ci.org/hawkular/hawkular.svg["Build Status", link="https://travis-ci.org/hawkular/hawkular"]
endif::[]

== License

Hawkular is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




