= Hawkular Console

[.lead]
*Hawkular Console* is the home of the UI console for Hawkular.  The current console is based on https://github.com/hawtio/hawtio/blob/master/docs/Overview2dotX.md[Hawt.io 2], which is (now) a javascript based client-side framework.
This console application pulls in various bower packages (libs) and Hawt.io 2 plugins (which are also bower packages) to plug-n-play various functionality to the console. Since one of the bower packages it pulls in is our Hawt.io plugin, it loads this plugin and adds it to the nav bar.

== UI Directory Structure

* ui - directory for various Hawkular UIs (currently only one)

** ui/console - The Hawkular UI console - which consumes bower components from https://github.com/hawkular/hawkular-ui-components[hawkular-ui-components]

The general idea here being hawt.io UIs which are composed of plugins (that can swapped around like legos between the various UIs)

== Maven Install

The easiest way to build the console is to use maven (inside the `console` directory):

`mvn install`

No system http://nodejs.org/[Node.js] dependencies are needed.
http://nodejs.org/[Node.js] and its related modules are managed by the https://github.com/eirslett/frontend-maven-plugin[frontend-maven-plugin].
They are downloaded to the build target (./console/target) directory, where the actual http://gulpjs.com/[Gulp] based build process
(triggered by the maven plugin) happens.

To save some time during the build process, the downloaded http://nodejs.org/[Node.js] files and its related modules
don't have to be deleted after invoking the `clean` target. If you want to persist the node.js related stuff in the target
directory, please use the `cache` profile:

`mvn clean -Pcache`

In that case, the http://nodejs.org/[Node.js] is not deleted and doesn't have to be downloaded again, together with
npm modules and bower packages. Be aware, this causes the libraries not being updated.

After the console is built, you can access it by traversing to the the build target (./console/target/gulp-build) directory:

`cd console/target/gulp-build`

and running the appropriate gulp (default) target:

`gulp`

After those steps, the console is available on http://localhost:2772/[http://localhost:2772/], but be aware that
it's only a front-end and you need the server running for console to work properly. The advantage of this approach is,
that is scans for file changes in the source directory and apply them directly into the target directory, which is
suitable for console developing since it doesn't require the whole maven build to see the actual changes in the console UI.

== Hawkular-ui-components development

If you want to use your local version of hawkular-ui-components, you can use the `link` profile and the
https://oncletom.io/2013/live-development-bower-component/[bower link functionality]. In the hawkular-ui-components,
link your bower package with:

`bower link`

and then build the kettle with:

`mvn clean install -Plink`

== Dev Install

You can still re-build the console using only java-script based tools. Please do that only after maven build and
only within the build target (./console/target/gulp-build) directory. These steps are rarely used and if you're not
an hawkular console developer you most probably won't need it.

Assuming the node.js is already installed:

`npm install -g bower gulp typescript`

Install the cli commands globally

`cd console/target`

`npm install`

Install the local npm packages

`bower install`

Install the local bower packages for the application

`gulp`

Run the application and 'watch' the source tree for any changes refreshing the browser if any changes

In browser: Navigate to http://localhost:2772/

Profit!

For further detail the hawt.io plugin structure is described https://github.com/hawtio/hawtio/blob/master/docs/Overview2dotX.md[here].


_The maven plugin for running frontend npm/bower installs is underway as well_
